### ISSUE TITLE
Reported recipients for iOS is app id and not product id...?

### ISSUE THREAD

**Issue by HarelM** [Fovea/Billing#1]
I'm getting the following recipient for iOS which is driving me crazy:

2020-03-29 @ 07:41 |   | Receipt validated il.org.osm.israelhiking on ios.
My product is offline_map and sometimes it does show that for iOS but most of the time it doesn't.

Can this be checked please?
My code can be seen here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/services/purchase.service.ts

It's pretty simple and straight forward as far as I understand, any help would be appreciated.
You can see in the file's history my attempts to fix this. None of them worked unfortunately. :-(

**Comment by j3k0** [comment]
This has been answered on the plugin issues page.

Concerning your issue about cluttering the customers page. I understand. There's the idea in the backlog to only add filters to that page: like showing only users that owns a given product, that are subscribers, lapsed, sandbox/prod, etc.

**Comment by HarelM** [comment]
Thanks for the info and response.
Feel free to close this issue, I though it was a bug in my code that caused this.
Filtering this page would be an ideal solution for me, thanks!

**Comment by j3k0** [comment]
> I though it was a bug in my code that caused this.

You're not the first, we have to do something about that.
