### ISSUE TITLE
Events are not sorted by date in Customer screen?

### ISSUE THREAD

**Issue by HarelM** [Fovea/Billing#2]
I have the following events that are not sorted well I believe.
See screenshot below - this is a table after entering to see a specific customer from the customers screen.
Might be because some of the validation is on android while the others are on iOS snadbox...?
![image](https://user-images.githubusercontent.com/3269297/78600049-e0ac4f00-785a-11ea-9141-eade4929675c.png)

**Comment by j3k0** [comment]
Thanks for the report.

The transactions are kept in order of "discovery". I interpret it as this given "google" user logging in your app on Android, maybe for the first time using this `applicationUsername`, after using the app on iOS. He might have been using another account when he purchased the product on Android. Maybe it did before you setup Fovea's receipt validator.

As usual, is it a bug or a feature is up for debate :-) I agree it looks a bit weird.

**Comment by HarelM** [comment]
I personally know this user and I can describe his interaction with the app according to a timeline and this doesn't add up.
I setup fovea billing along side the app purchase feature so the server was there from day one (about a month ago).
The user used his google account on his android app to purchase first as can be seen in the date.
Later on his used a test account on iOS as can also be seen in the dates too.
In any case, bug or feature, we both agree it looks weird :-)

**Comment by j3k0** [comment]
This is fixed
