### ISSUE TITLE
Refreshing Customers view gives inconsistent results 

### ISSUE THREAD

**Issue by HarelM** [Fovea/Billing#3]
When clicking the browser refresh button when in Customers screen (Where you see all the customers), the order of the customers in the screen sometimes changes.
Hitting refresh again will change the order to be by customers' addition order, but sometimes it doesn't.
This is relatively easy to reproduce.
1. Go to the [customers list screen](https://billing-dashboard.fovea.cc/customers)
2. Hit the browser refresh button a few times
3. The order in the list will change after a few refreshes

Why am I reporting this? well, I have the customers screen open in my browser and I hit refresh to see if I have new customers every few days. When I hit refresh and nothing changes I know no new customers have payed, When something changes in the screen I automatically think a new customer joined only to find out only the order had changed...

**Comment by j3k0** [comment]
Thanks for the report. We'll make the order on this list stay consistent. Easy fix I believe.

**Comment by HarelM** [comment]
Seems like the transaction screen behaves the same.
Probably the same fix should be applied there...

**Comment by j3k0** [comment]
Fixed.
