### ISSUE TITLE
Event timeline table should use "." instead of "/"

### ISSUE THREAD

**Issue by HarelM** [Fovea/Billing#4]
This is nitpicking, I know, but the following table should have the "." mark instead of the "/", right?
i.e. "1. app.fetch, 2. ..."
![image](https://user-images.githubusercontent.com/3269297/81492841-dc34e500-92a3-11ea-98ee-dc0e5e09ced6.png)
This is the table below an event.

**Comment by j3k0** [comment]
Thanks for taking time to report this. Whatever typo is chosen, it has to match the one from above (External Requests).

<img width="896" alt="Screen Shot 2020-05-11 at 12 07 21" src="https://user-images.githubusercontent.com/191881/81544276-fb08a980-937f-11ea-8d77-75a4aca0eeb3.png">
